### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by sshaw** [mattduck/org-toggl-py#1]
Note that I updated your script to call `python3` as with `python` (v2.7) I was getting:

```
Traceback (most recent call last):
  File "org-toggl.py", line 11, in <module>
    import requests
ImportError: No module named requests
```

With `python3` I get:
```
~/code/elisp/org-toggl-py >python3 --version
Python 3.7.3
~/code/elisp/org-toggl-py >./org-toggl.sh config.ini ~/Documents/Jobs/xxxxxxxx/xxxxxxxx.org
Exporting to JSON: /Users/sshaw/Documents/Jobs/xxxxxxxx/xxxxxxxx.org
Traceback (most recent call last):
  File "org-toggl.py", line 7, in <module>
    from ConfigParser import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

**Comment by mattduck** [comment]
Hi! Thanks for the issue. I haven't worked on this project for a long time, not sure if it still works with the Toggl API. I'll try to investigate this week and update for Python 3.

```
ImportError: No module named requests
```

This error on 2.7 suggests that some Python dependencies aren't installed - you could run `pip install -r requirements.txt` (https://github.com/mattduck/org-toggl-py/blob/master/requirements.txt), although those package versions are quite old now so you might just want to run `pip install` manually on the required packages.

**Comment by sshaw** [comment]
> ImportError: No module named requests
> This error on 2.7 suggests that some Python dependencies aren't installed ...

They were.
